import { Product } from './store';

export const PRODUCTS: Product[] = [
  {
    id: 'bb-001',
    name: 'BIGBOLD Classic Tee',
    price: 12500,
    originalPrice: 15000,
    category: 'Tops',
    subcategory: 'T-Shirts',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
      'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White'],
    description: 'The original BIGBOLD statement tee. Heavyweight 320gsm cotton, oversized silhouette, screen-printed logo. This is the piece that started it all.',
    details: ['320gsm 100% Cotton', 'Oversized fit', 'Screen-printed graphics', 'Pre-washed for softness', 'Made in Nigeria'],
    rating: 4.9,
    reviews: 128,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    tags: ['tee', 'classic', 'bestseller', 'cotton'],
  },
  {
    id: 'bb-002',
    name: 'Quiet Confidence Hoodie',
    price: 28000,
    category: 'Tops',
    subcategory: 'Hoodies',
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&q=80',
      'https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=800&q=80',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Charcoal'],
    description: 'In a world full of noise, sometimes the quietest voice is the loudest. This heavyweight hoodie embodies that philosophy.',
    details: ['400gsm French Terry', 'Kangaroo pocket', 'Ribbed cuffs and hem', 'Embroidered logo', 'Unisex fit'],
    rating: 4.8,
    reviews: 94,
    inStock: true,
    isNew: true,
    isBestSeller: false,
    tags: ['hoodie', 'heavyweight', 'new'],
  },
  {
    id: 'bb-003',
    name: 'Unapologetic Cargo Pants',
    price: 35000,
    category: 'Bottoms',
    subcategory: 'Pants',
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=80',
      'https://images.unsplash.com/photo-1594938298603-c8148c4b4f7f?w=800&q=80',
    ],
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['Black', 'Olive'],
    description: 'Utility meets style. Six-pocket cargo silhouette with a relaxed fit that moves with you.',
    details: ['Heavy cotton twill', '6 functional pockets', 'Adjustable ankle cuffs', 'Metal hardware', 'Relaxed fit'],
    rating: 4.7,
    reviews: 67,
    inStock: true,
    isNew: true,
    isBestSeller: false,
    tags: ['cargo', 'pants', 'utility', 'new'],
  },
  {
    id: 'bb-004',
    name: 'Sophistication Simplified Cap',
    price: 8500,
    category: 'Accessories',
    subcategory: 'Headwear',
    images: [
      'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&q=80',
      'https://images.unsplash.com/photo-1534215754734-18e55d13e346?w=800&q=80',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'White', 'Cream'],
    description: 'The BIGBOLD 6-panel cap. Clean lines, embroidered logo, adjustable strap.',
    details: ['6-panel construction', 'Embroidered BIGBOLD logo', 'Adjustable snapback', 'Structured brim', 'One size fits most'],
    rating: 4.6,
    reviews: 203,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    tags: ['cap', 'accessories', 'headwear', 'bestseller'],
  },
  {
    id: 'bb-005',
    name: 'EST. 2023 Graphic Tee',
    price: 13500,
    category: 'Tops',
    subcategory: 'T-Shirts',
    images: [
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80',
      'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'White', 'Cream'],
    description: 'Marking the beginning. The EST. 2023 tee celebrates the founding year of BIGBOLD with archival-inspired graphics.',
    details: ['280gsm Cotton', 'Vintage wash', 'Front and back graphics', 'Boxy fit', 'Limited run'],
    rating: 4.8,
    reviews: 156,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    tags: ['tee', 'graphic', 'limited', 'bestseller'],
  },
  {
    id: 'bb-006',
    name: 'Lifestyle Bomber Jacket',
    price: 65000,
    originalPrice: 75000,
    category: 'Outerwear',
    subcategory: 'Jackets',
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80',
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black'],
    description: 'More than a brand. A lifestyle. The BIGBOLD bomber is the statement piece your wardrobe has been waiting for.',
    details: ['Satin shell', 'Ribbed collar, cuffs and hem', 'Embroidered patches', 'Interior zip pocket', 'Unisex cut'],
    rating: 5.0,
    reviews: 42,
    inStock: true,
    isNew: true,
    isBestSeller: false,
    tags: ['jacket', 'bomber', 'outerwear', 'new', 'premium'],
  },
  {
    id: 'bb-007',
    name: 'Weird Sketch Crewneck',
    price: 22000,
    category: 'Tops',
    subcategory: 'Sweatshirts',
    images: [
      'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80',
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&q=80',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White'],
    description: 'When a weird sketch turned into stunning merch. The crewneck that started as a doodle and became a movement.',
    details: ['360gsm fleece', 'Ribbed collar and cuffs', 'Screen-printed artwork', 'Dropped shoulders', 'Unisex'],
    rating: 4.9,
    reviews: 88,
    inStock: true,
    isNew: false,
    isBestSeller: false,
    tags: ['crewneck', 'sweatshirt', 'graphic'],
  },
  {
    id: 'bb-008',
    name: 'BIGBOLD Tote Bag',
    price: 6500,
    category: 'Accessories',
    subcategory: 'Bags',
    images: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'Cream'],
    description: 'Carry the brand. Heavy canvas tote with screen-printed BIGBOLD logo.',
    details: ['Heavy canvas', 'Screen-printed logo', 'Reinforced handles', '40cm x 35cm', 'Interior pocket'],
    rating: 4.5,
    reviews: 312,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    tags: ['tote', 'bag', 'accessories', 'bestseller'],
  },
  {
    id: 'bb-009',
    name: 'Confidence Shorts',
    price: 16000,
    category: 'Bottoms',
    subcategory: 'Shorts',
    images: [
      'https://images.unsplash.com/photo-1591195853828-11db59a44f43?w=800&q=80',
      'https://images.unsplash.com/photo-1562886877-f3b2e7e5e3e5?w=800&q=80',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Olive', 'Cream'],
    description: 'Relaxed fit shorts for the confident individual. Elastic waist, side pockets, BIGBOLD embroidery.',
    details: ['Cotton blend', 'Elastic waistband with drawstring', 'Side and back pockets', 'Embroidered logo', '9" inseam'],
    rating: 4.6,
    reviews: 74,
    inStock: true,
    isNew: false,
    isBestSeller: false,
    tags: ['shorts', 'bottoms', 'summer'],
  },
  {
    id: 'bb-010',
    name: 'Noise Cancelling Beanie',
    price: 7500,
    category: 'Accessories',
    subcategory: 'Headwear',
    images: [
      'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=800&q=80',
      'https://images.unsplash.com/photo-1510598155-b9e7e5e5e5e5?w=800&q=80',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'White', 'Charcoal'],
    description: 'Block out the noise. Ribbed knit beanie with woven BIGBOLD label.',
    details: ['100% Acrylic', 'Ribbed knit', 'Woven label', 'One size fits most', 'Unisex'],
    rating: 4.7,
    reviews: 189,
    inStock: true,
    isNew: false,
    isBestSeller: false,
    tags: ['beanie', 'accessories', 'headwear', 'winter'],
  },
  {
    id: 'bb-011',
    name: 'Lifestyle Long Sleeve',
    price: 15000,
    category: 'Tops',
    subcategory: 'Long Sleeves',
    images: [
      'https://images.unsplash.com/photo-1618354691438-25bc04584c23?w=800&q=80',
      'https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=800&q=80',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Cream'],
    description: 'The everyday essential. Heavyweight long sleeve with subtle BIGBOLD branding.',
    details: ['300gsm Cotton', 'Ribbed cuffs', 'Chest logo embroidery', 'Relaxed fit', 'Pre-shrunk'],
    rating: 4.8,
    reviews: 97,
    inStock: true,
    isNew: true,
    isBestSeller: false,
    tags: ['longsleeve', 'tops', 'new', 'essential'],
  },
  {
    id: 'bb-012',
    name: 'BIGBOLD Socks (3-Pack)',
    price: 4500,
    category: 'Accessories',
    subcategory: 'Socks',
    images: [
      'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=800&q=80',
      'https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=800&q=80',
    ],
    sizes: ['S/M', 'L/XL'],
    colors: ['Black', 'White', 'Mixed'],
    description: 'Complete the fit. BIGBOLD branded crew socks, 3-pack.',
    details: ['80% Cotton 20% Elastane', 'Ribbed cuff', 'Woven BIGBOLD logo', 'Reinforced heel and toe', '3 pairs per pack'],
    rating: 4.4,
    reviews: 445,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    tags: ['socks', 'accessories', 'bestseller'],
  },
];

export const SORT_OPTIONS = ['Featured', 'Price: Low to High', 'Price: High to Low', 'Newest', 'Best Sellers', 'Top Rated'];

export function formatPrice(price: number): string {
  return `₦${price.toLocaleString()}`;
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find(p => p.id === id);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS
    .filter(p => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}
